[tool.poetry]
name = "pynescript"
version = "0.1.0"
description = ""
authors = ["Yunseong Hwang <kika1492@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
pyparsing = "^3.0.9"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
